# 03 - `props`: additive properties of the Components
The user can add properties such as price, density, etc., that can be weighted by quantity and summed for optimization purposes.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')

import json

from blends.base import dict_to_blend, blend_to_dict

myblend_dict = json.load(open('../data/blend_example_003.json'))
myblend = dict_to_blend(myblend_dict)

In [3]:
from blends.sample import get_samples_both

df_samples = get_samples_both(myblend, verbose=True)
df_samples

5000 - 2739 invalid - 2225 redundant = 36: successful samples generated.
1000 - 491 invalid - 0 redundant = 509: successful samples generated.

,Solvent-1,Solvent-2,Solvent-3,Comp-A1,Comp-A2,Comp-A3,Component-B,Qtot
0,0.2,0.000,0.000,0.700,0.000,0.000,0.100,1.0
1,0.3,0.000,0.000,0.000,0.000,0.400,0.300,1.0
2,0.0,0.300,0.000,0.000,0.400,0.000,0.300,1.0
3,0.3,0.000,0.000,0.600,0.000,0.000,0.100,1.0
4,0.0,0.200,0.000,0.000,0.700,0.000,0.100,1.0
...,...,...,...,...,...,...,...,...
504,0.0,0.286,0.000,0.178,0.217,0.027,0.292,1.0
505,0.0,0.204,0.000,0.001,0.103,0.503,0.189,1.0
506,0.0,0.222,0.000,0.485,0.177,0.011,0.105,1.0
507,0.0,0.000,0.247,0.025,0.296,0.225,0.207,1.0
508,0.0,0.000,0.278,0.132,0.154,0.318,0.118,1.0

In [4]:
# Compute the weighted sum of the propery "price"
from blends.sample import add_prop_to_samples

df_samples_price = add_prop_to_samples(myblend, df_samples, prop_name="price")
df_samples_price.sort_values(by="price", ascending=True)

,Solvent-1,Solvent-2,Solvent-3,Comp-A1,Comp-A2,Comp-A3,Component-B,Qtot,price
7,0.000,0.0,0.300,0.000,0.000,0.400,0.300,1.000,11.8100
8,0.000,0.3,0.000,0.000,0.000,0.400,0.300,1.000,12.0500
1,0.300,0.0,0.000,0.000,0.000,0.400,0.300,1.000,12.2900
23,0.000,0.0,0.200,0.000,0.000,0.400,0.400,1.000,12.5400
395,0.000,0.0,0.297,0.005,0.059,0.347,0.292,1.000,12.6819
...,...,...,...,...,...,...,...,...,...
184,0.213,0.0,0.000,0.584,0.028,0.068,0.107,1.000,33.3859
213,0.000,0.0,0.213,0.612,0.025,0.022,0.129,1.001,33.6551
36,0.000,0.0,0.200,0.700,0.000,0.000,0.100,1.000,36.5400
10,0.000,0.2,0.000,0.700,0.000,0.000,0.100,1.000,36.7000
0,0.200,0.0,0.000,0.700,0.000,0.000,0.100,1.000,36.8600

In [5]:
# Add a new property to the root Blend and compute it for the samples
from blends.base import add_prop_to_blend
from copy import deepcopy

prop_name = "price2"
prop_description = " Property: price2 (alternative price in $/kg)."
prop_dict = {
    "Solvent-1": 0.5,
    "Solvent-2": 0.6,
    "Solvent-3": 0.7,
    "Comp-A1": 1.0,
    "Comp-A2": 2.0,
    "Comp-A3": 3.0,
    "Comp-B1": 2.0,
    "Component-B": 4.0,
}

myblend2 = deepcopy(myblend)
myblend2.description += prop_description
add_prop_to_blend(myblend2, prop_name, prop_dict)

blend_to_dict(myblend2)

{'name': 'myRootBlend',
 'description': 'An example of a Blend. Properties: price ($/kg). Property: price2 (alternative price in $/kg).',
 'children': [{'name': 'Solvent',
   'description': 'Choose only one of the 3 following solvents',
   'children': [{'name': 'Solvent-1',
     'description': 'xxx',
     'qmin': 0,
     'qmax': 1,
     'props': {'price': 4.3, 'price2': 0.5}},
    {'name': 'Solvent-2',
     'description': 'yyy',
     'qmin': 0,
     'qmax': 1,
     'props': {'price': 3.5, 'price2': 0.6}},
    {'name': 'Solvent-3',
     'description': 'zzz',
     'qmin': 0,
     'qmax': 1,
     'props': {'price': 2.7, 'price2': 0.7}}],
   'qmin': 0.2,
   'qmax': 0.3,
   'cmax': 1},
  {'name': 'Blend-A',
   'description': 'Mix the following A components',
   'children': [{'name': 'Comp-A1',
     'description': 'xxx',
     'qmin': 0,
     'qmax': 1,
     'props': {'price': 50.0, 'price2': 1.0}},
    {'name': 'Comp-A2',
     'description': 'yyy',
     'qmin': 0,
     'qmax': 1,
     'props': {'price': 30.0, 'price2': 2.0}},
    {'name': 'Comp-A3',
     'description': 'zzz',
     'qmin': 0,
     'qmax': 1,
     'props': {'price': 20.0, 'price2': 3.0}}],
   'qmin': 0.4,
   'qmax': 0.7,
   'cmax': 3},
  {'name': 'Component-B',
   'description': 'zzz',
   'qmin': 0.1,
   'qmax': 0.6,
   'props': {'price': 10.0, 'price2': 4.0}}],
 'qmin': 1.0,
 'qmax': 1.0,
 'cmax': 3}

In [6]:
df_samples_price2 = add_prop_to_samples(myblend2, df_samples, prop_name="price2")
df_samples_price2.sort_values(by="price2", ascending=True)

,Solvent-1,Solvent-2,Solvent-3,Comp-A1,Comp-A2,Comp-A3,Component-B,Qtot,price2
3,0.3,0.0,0.000,0.600,0.000,0.000,0.100,1.000,1.1500
38,0.0,0.3,0.000,0.600,0.000,0.000,0.100,1.000,1.1800
0,0.2,0.0,0.000,0.700,0.000,0.000,0.100,1.000,1.2000
16,0.0,0.0,0.300,0.600,0.000,0.000,0.100,1.000,1.2100
10,0.0,0.2,0.000,0.700,0.000,0.000,0.100,1.000,1.2200
...,...,...,...,...,...,...,...,...,...
162,0.0,0.0,0.219,0.005,0.074,0.327,0.375,1.000,2.7873
492,0.0,0.0,0.215,0.019,0.016,0.385,0.366,1.001,2.8205
48,0.2,0.0,0.000,0.000,0.000,0.400,0.400,1.000,2.9000
71,0.0,0.2,0.000,0.000,0.000,0.400,0.400,1.000,2.9200
23,0.0,0.0,0.200,0.000,0.000,0.400,0.400,1.000,2.9400